### ISSUE TITLE
Error with point geometry

### ISSUE THREAD

**Issue by leoruizb** [tomchadwin/qgis2web#364]
Hi

I am working with QGIS 2.8 and I am trying to use the Qgis2web plugin for a simple layer (póint geometry) but I get this error over and over.  I tried with qgis2web version 1.8 and 1.9 and get the same error.

I make another point geometry layer and get the same problem. With line and polygon I don´t get any error, only with point.

**Error**

qgis2web produced an error:

Traceback (most recent call last):
File "C:/Users/LeoI5/.qgis2/python/plugins\qgis2web\maindialog.py", line 138, in previewMap
MainDialog.previewLeaflet(self)
File "C:/Users/LeoI5/.qgis2/python/plugins\qgis2web\maindialog.py", line 348, in previewLeaflet
visible, cluster, json, params, popup)
File "C:/Users/LeoI5/.qgis2/python/plugins\qgis2web\leafletWriter.py", line 159, in writeLeaflet
canvas, lyrCount)
File "C:/Users/LeoI5/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 285, in writeVectorLayer
legends, count, popFuncs, zIndex)
File "C:/Users/LeoI5/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 475, in singleLayer
zIndex)
File "C:/Users/LeoI5/.qgis2/python/plugins\qgis2web\leafletLayerScripts.py", line 534, in singlePoint
rot = symbol.dataDefinedAngle().expressionOrField()
AttributeError: 'QgsMarkerSymbolV2' object has no attribute 'dataDefinedAngle'

How can I solve this problem?
thanks
bye

Leo

**Comment by tomchadwin** [comment]
Can you upload your layer and project somewhere? I can then take a look at it and see what the problem is. I've seen this issue before, and it is possibly already fixed in the master branch here. I'll check.

**Comment by tomchadwin** [comment]
Ah, what marker type are you using?

**Comment by leoruizb** [comment]
Hi
I need to use the qgis2web version 1.18 because it easy for me to change the code than the new version 1.19.  I used to add google earth background satellite image and drone images too.
You can see an example here:
http://www.geoeduca.org/demosigdrones/penadeoro/
I solve the problem using QGIS 2.18 but I still want to solve the problem using qgis 2.08 and qgis2web v1.18
I will send you the shape
thanks
bye
Leo

**Comment by tomchadwin** [comment]
I'll take a look at it when you send it over. I should say, though, that QGIS 2.8 is no longer supported, and you should either be using 2.14 or 2.18.

**Comment by tomchadwin** [comment]
The same applies to qgis2web 1.18. I will only fix the current version 1.19.0. If there is a reason that you choose not to use the latest version (has there been a regression I don't know about?), then do let me know.

**Comment by leoruizb** [comment]
Yes, you are right.  I will change all my computers to qgis 2.14.  Then I will tell you if I solve the problem.

With the new version 1.19.0 now I had the problem the js+leaflet code I use to add to get the google satelite maps (see the link I send you before) it doesn't work any more.  I don't know why.

thanks. bye. Leo

**Comment by tomchadwin** [comment]
The Google plugin doesn't work because 1.19 uses Leaflet 1.0, while 1.18 used Leaflet 0.7. I can't really help you with that, other than perhaps to point you towards this comment:

https://gist.github.com/crofty/2197042#gistcomment-1818028

**Comment by tomchadwin** [comment]
Closing until layer and project uploaded.

**Comment by leoruizb** [comment]
Hi.
Sorry I had to travel outside my office for a week
Thanks for your help.  I really apreciate your usefull tips.
I solved the problem
bye
Leo

**Comment by tomchadwin** [comment]
Glad you got it sorted, and thanks for reporting back.
