### PR TITLE
Rasters not stylized #148

### PR DESCRIPTION
**Pull request by lucacasagrande**
Should fix raster's export. Please test :)

### CODE REVIEW

**Comment by lucacasagrande** [comment]
@tomchadwin in 2.8.9 there is a problem with  `from qgis.core import QgsExpressionContext`
It was introduced here b4d15f754aea5f0c8e9e3d779e7c9f369de3fc21 What do you think about?

**Comment by tomchadwin** [comment]
Have you used `QgsExpressionContext` in your commits? I assume not? It is used for the 2.5d output. 2.5d is only possible in 2.14+.

Do I therefore deduce that this is a cosmetic problem resulting from your getting rid of the `*` import, meaning you are explicitly importing `QgsExpressionContext` by name?

If so, what is the best solution? We obviously need to get rid of `*` imports in preparation for Python 3. Are conditional imports syntactic and PEP8 compliant?

**Comment by tomchadwin** [comment]
Or wrap that specific import in a `try`? This can't be an unknown situation.

**Comment by lucacasagrande** [comment]
We can use a "version check" and import the modules that we need. I think that it can be done during a major refactoring, for example for release 2.0.0.

**Comment by tomchadwin** [comment]
My first test did not work in a slightly elderly master (29df8a9). I used this raster:

test

 Console says:

```
Error: Wrong number of parametersError: Wrong number of parameters
ALGORITHM: Warp (reproject)
	INPUT <ParameterRaster>
	SOURCE_SRS <ParameterCrs>
	DEST_SRS <ParameterCrs>
	NO_DATA <ParameterString>
	TR <ParameterNumber>
	METHOD <ParameterSelection>
	RTYPE <ParameterSelection>
	COMPRESS <ParameterSelection>
	JPEGCOMPRESSION <ParameterNumber>
	ZLEVEL <ParameterNumber>
	PREDICTOR <ParameterNumber>
	TILED <ParameterBoolean>
	BIGTIFF <ParameterSelection>
	TFW <ParameterBoolean>
	EXTRA <ParameterString>
	OUTPUT <OutputRaster>


METHOD(Resampling method)
	0 - near
	1 - bilinear
	2 - cubic
	3 - cubicspline
	4 - lanczos
RTYPE(Output raster type)
	0 - Byte
	1 - Int16
	2 - UInt16
	3 - UInt32
	4 - Int32
	5 - Float32
	6 - Float64
COMPRESS(GeoTIFF options. Compression type:)
	0 - NONE
	1 - JPEG
	2 - LZW
	3 - PACKBITS
	4 - DEFLATE
BIGTIFF(Control whether the created file is a BigTIFF or a classic TIFF)
	0 - 
	1 - YES
	2 - NO
	3 - IF_NEEDED
	4 - IF_SAFER

Unable to execute algorithm
Wrong parameter value: c:\users\tchadwin\appdata\local\temp\test1466769134_piped_3857.tif

ALGORITHM: Warp (reproject)
	INPUT <ParameterRaster>
	SOURCE_SRS <ParameterCrs>
	DEST_SRS <ParameterCrs>
	NO_DATA <ParameterString>
	TR <ParameterNumber>
	METHOD <ParameterSelection>
	RTYPE <ParameterSelection>
	COMPRESS <ParameterSelection>
	JPEGCOMPRESSION <ParameterNumber>
	ZLEVEL <ParameterNumber>
	PREDICTOR <ParameterNumber>
	TILED <ParameterBoolean>
	BIGTIFF <ParameterSelection>
	TFW <ParameterBoolean>
	EXTRA <ParameterString>
	OUTPUT <OutputRaster>


METHOD(Resampling method)
	0 - near
	1 - bilinear
	2 - cubic
	3 - cubicspline
	4 - lanczos
RTYPE(Output raster type)
	0 - Byte
	1 - Int16
	2 - UInt16
	3 - UInt32
	4 - Int32
	5 - Float32
	6 - Float64
COMPRESS(GeoTIFF options. Compression type:)
	0 - NONE
	1 - JPEG
	2 - LZW
	3 - PACKBITS
	4 - DEFLATE
BIGTIFF(Control whether the created file is a BigTIFF or a classic TIFF)
	0 - 
	1 - YES
	2 - NO
	3 - IF_NEEDED
	4 - IF_SAFER

Unable to execute algorithm
Wrong parameter value: c:\users\tchadwin\appdata\local\temp\test1466769131_piped_3857.tif
```
Any ideas?

**Comment by tomchadwin** [comment]
Can you share your test raster(s)/style(s)?

**Comment by tomchadwin** [comment]
Ah, but it works in 2.14.3. Nice!

**Comment by tomchadwin** [comment]
Updated to latest nightly 92bfcd4. Still not working. How does it pass the Travis nightly test? Wondering whether my setup has a different combination of QGIS nightly plus GDAL (Windows) which makes it fail, given that I have it alongside 2.14.3, compared to a fresh Travis install on Linux.

**Comment by tomchadwin** [comment]
No such complex explanation necessary, of course. There are no raster tests in the test suite, so the failure in master won't be triggered.

**Comment by lucacasagrande** [comment]
Hi Tom, thanks for testing!
It's strange, it works for me with master from 2 days ago. I tested using data from https://github.com/tomchadwin/qgis2web/issues/148#issuecomment-204714055 .
I will take a look if the gdal parameters have changed during the last days.

**Comment by tomchadwin** [comment]
Great. I'm trying to get a raster test working in the tomchadwin master branch, but I haven't got it right yet - I suspect projection issues. Once I have one, it should help.

**Comment by tomchadwin** [comment]
No, I'm getting beyond my knowledge. I might have fixed the CRS issue, butt he test now gives me:

```
File "/home/travis/build/tomchadwin/qgis2web/olwriter.py", line 58, in writeOL
1090    optimize, usedFields, json)
1091  File "/home/travis/build/tomchadwin/qgis2web/utils.py", line 205, in exportLayers
1092    prov_raster)
1093  File "/usr/share/qgis/python/plugins/processing/tools/general.py", line 75, in runalg
1094    alg = Processing.runAlgorithm(algOrName, None, *args, **kwargs)
1095  File "/usr/share/qgis/python/plugins/processing/core/Processing.py", line 213, in runAlgorithm
1096    alg = Processing.getAlgorithm(algOrName)
1097  File "/home/travis/build/tomchadwin/qgis2web/test/qgis_interface.py", line 99, in mock_getAlgorithm
1098    for provider in Processing.algs.values():
1099AttributeError: 'function' object has no attribute 'values'
```

Not sure I like the look of `mock_getAlgorithm` - I don't know whether processing is even available in the test environment. If not, I don't know how to set it up.

Sorry, not sure a raster test is likely to appear soon, I'm afraid.

**Comment by lucacasagrande** [comment]
Ok, no problem. Later today I will try with current master and I will keep you updated. Have you got a 2.8 to test?

**Comment by tomchadwin** [comment]
I'm on Windows, and I've not managed to run 2.8 alongside 2.14/nightly because of processing version conflicts. However, I'm just spinning up an Ubuntu VM, which I think has 2.8 on it. I'll report back soon.

**Comment by tomchadwin** [comment]
Works in 2.8.9! Brilliant!

**Comment by lucacasagrande** [comment]
Nice, thanks for testing :)

**Comment by tomchadwin** [comment]
OK, I've got the raster test working, so Travis should test your PRs. It is passing on 2.8 and 2.14, but failing on dev, which is what I have found with my manual tests. Hope it helps.

**Comment by lucacasagrande** [comment]
Hi Tom, I just tested the plugin with QGIS-master and it works fine. Can please post the list of the parameters of gdalwarp alg? Thanks

**Comment by lucacasagrande** [comment]
I think it's something related to testing..The build failed with:

`for provider in Processing.algs.values():`
`AttributeError: 'function' object has no attribute 'values'`

This is working in QGIS-master:
`Processing.algs().values()`

Can this be the problem?

**Comment by tomchadwin** [comment]
Running 92bfcd4 locally, OL3 gives me:

```
('gdalogr:warpreproject', u'c:\\users\\tchadwin\\appdata\\local\\temp\\test1466801550_piped.tif', u'EPSG:3857', 'EPSG:3857', '', 0, 0, u'-234984.529972,-233243.512382,7356155.40159,7357901.64223', 'EPSG:3857', 0, 4, 75, 6, 1, False, 0, False, '', u'c:\\users\\tchadwin\\appdata\\local\\temp\\test1466801550_piped_3857.tif')
```

Leaflet:

```
('gdalogr:warpreproject', u'c:\\users\\tchadwin\\appdata\\local\\temp\\test01466801735_piped.tif', u'EPSG:3857', 'EPSG:3857', '', 0, 0, u'-234984.529972,-233243.512382,7356155.40159,7357901.64223', 'EPSG:3857', 0, 4, 75, 6, 1, False, 0, False, '', u'c:\\users\\tchadwin\\appdata\\local\\temp\\test01466801735_piped_3857.tif')
```

**Comment by lucacasagrande** [comment]
Everything it's fine with the parameters..I tried test.png and it creates the map without errors.

**Comment by tomchadwin** [comment]
Error for both OL3 and Leaflet is

```
Error: Wrong number of parameters
Unable to execute algorithm
Wrong parameter value: c:\users\tchadwin\appdata\local\temp\test1466801726_piped_3857.tif
```

**Comment by tomchadwin** [comment]
Try pulling down the aux.xml next to the PNG, and then opening it in QGIS. Does that make a difference?

**Comment by lucacasagrande** [comment]
Working fine also with xml. Can please post the output of:
`import processing`
`processing.alghelp("gdalogr:warpreproject")`

**Comment by tomchadwin** [comment]
```
import processing
processing.alghelp("gdalogr:warpreproject") 
ALGORITHM: Warp (reproject)
	INPUT <ParameterRaster>
	SOURCE_SRS <ParameterCrs>
	DEST_SRS <ParameterCrs>
	NO_DATA <ParameterString>
	TR <ParameterNumber>
	METHOD <ParameterSelection>
	RTYPE <ParameterSelection>
	COMPRESS <ParameterSelection>
	JPEGCOMPRESSION <ParameterNumber>
	ZLEVEL <ParameterNumber>
	PREDICTOR <ParameterNumber>
	TILED <ParameterBoolean>
	BIGTIFF <ParameterSelection>
	TFW <ParameterBoolean>
	EXTRA <ParameterString>
	OUTPUT <OutputRaster>


METHOD(Resampling method)
	0 - near
	1 - bilinear
	2 - cubic
	3 - cubicspline
	4 - lanczos
RTYPE(Output raster type)
	0 - Byte
	1 - Int16
	2 - UInt16
	3 - UInt32
	4 - Int32
	5 - Float32
	6 - Float64
COMPRESS(GeoTIFF options. Compression type:)
	0 - NONE
	1 - JPEG
	2 - LZW
	3 - PACKBITS
	4 - DEFLATE
BIGTIFF(Control whether the created file is a BigTIFF or a classic TIFF)
	0 - 
	1 - YES
	2 - NO
	3 - IF_NEEDED
	4 - IF_SAFER
```

**Comment by tomchadwin** [comment]
If I'm counting correctly, it wants 16 arguments, and we're giving it 18?

**Comment by tomchadwin** [comment]
By the way:

```
osgeo.gdal.VersionInfo()
'2010000'
```

**Comment by lucacasagrande** [comment]
Mine:
```
	INPUT <ParameterRaster>
	SOURCE_SRS <ParameterCrs>
	DEST_SRS <ParameterCrs>
	NO_DATA <ParameterString>
	TR <ParameterNumber>
	METHOD <ParameterSelection>
	RAST_EXT <ParameterExtent>
	EXT_CRS <ParameterCrs>
	RTYPE <ParameterSelection>
	COMPRESS <ParameterSelection>
	JPEGCOMPRESSION <ParameterNumber>
	ZLEVEL <ParameterNumber>
	PREDICTOR <ParameterNumber>
	TILED <ParameterBoolean>
	BIGTIFF <ParameterSelection>
	TFW <ParameterBoolean>
	EXTRA <ParameterString>
	OUTPUT <OutputRaster>
```
QGIS:
https://github.com/qgis/QGIS/blob/master/python/plugins/processing/algs/gdal/warp.py
It seems that you have the old version for the warp alg.

**Comment by tomchadwin** [comment]
I could understand that my local install could have different versions, given that it is side by side with 2.14. But what about Travis? That's installed from scratch. 

Or have you manually upgraded processing to a version later than what is bundled with QGIS dev?

**Comment by lucacasagrande** [comment]
For master I always use the version from GitHub repository. Can this be the difference?

**Comment by tomchadwin** [comment]
Ah, I guess so. Look at qgis2web's .travis.yml to see where it gets nightly from.


I'm just mailing the dev list about this.

**Comment by lucacasagrande** [comment]
I also think that test is failing for

`
for provider in Processing.algs.values():
`
`
AttributeError: 'function' object has no attribute 'values'
`

With master we should use:

`
Processing.algs().values()
`

**Comment by tomchadwin** [comment]
OK, we'll see if anyone has an explanation. I really don't. Could packaged nightlies differ from master?

**Comment by tomchadwin** [comment]
Failing only on master, or on nightly as well?

**Comment by lucacasagrande** [comment]
Job 3

**Comment by tomchadwin** [comment]
OK. More version checking required, then. Unless the `algs ()` method is also available in the other versions.

**Comment by tomchadwin** [comment]
@volaya, can you help?

**Comment by tomchadwin** [comment]
Can we just `try:` the newer call and `except:` the older?

**Comment by tomchadwin** [comment]
Switching to a dict as per @volaya's suggestion gives this in nightly:

```
Error: Wrong parameter value EPSG:3857 for parameter EXT_CRS.
Unable to execute algorithm
Wrong parameter value: c:\users\tchadwin\appdata\local\temp\test1467019294_piped_3857.tif
```

Looking into it now.

**Comment by tomchadwin** [comment]
Getting rid of the two "extra" args makes it work in my nightly:

```
warpArgs = {
    "INPUT": piped_file,
    "SOURCE_SRS": layer.crs().authid(),
    "DEST_SRS": "EPSG:3857",
    "NO_DATA": "",
    "TR": 0,
    "METHOD": 0,
    # "RAST_EXT": extentRepNew,
    # "EXT_CRS": "EPSG:3857",
    "RTYPE": 0,
    "COMPRESS": 4,
    "JPEGCOMPRESSION": 75,
    "ZLEVEL": 6,
    "PREDICTOR": 1,
    "TILED": False,
    "BIGTIFF": 0,
    "TFW": False,
    "EXTRA": "",
    "OUTPUT": piped_3857
}
processing.runalg("gdalogr:warpreproject", warpArgs)
```

That works. So how do we proceed? Obviously we can `try:` it, but it would be good to understand the cause.

**Comment by tomchadwin** [comment]
Updated to latest nightly 91c2d76. wrapped warp in a `try:`. 2.14 and nightly work locally. Travis nightly still fails.

I'm getting very confused...

**Comment by tomchadwin** [comment]
I've tweaked and tweaked, as you can see from all the commits over the last day. I think that the Travis nightly `warp` needs 17 arguments, not the 16 or 18 which other environments need. However, I just can't get it to work:

https://travis-ci.org/tomchadwin/qgis2web/jobs/140779265

I've asked on the dev mailing list, but I'm getting no reply. I'll try poking people on Gitter, but at this stage, perhaps we just need to abandon the nightly test, and release as it stands now.

Dev list question and follow-ups are here:

http://osgeo-org.1560.x6.nabble.com/Number-of-arguments-for-processing-gdalogr-warpreproject-td5273308.html#a5273736

**Comment by lucacasagrande** [comment]
Yes, you are right. With a new release (marked as experimental) we can have more people testing.
Anyhow during the weekend I will take a look on this topic.

**Comment by tomchadwin** [comment]
OK, I've reverted everything to my best guess of how it should all work. If, this weekend, you could test against QGIS master, I'd be very grateful. Also, if you have a better approach than my nested `try`s, great.

I've disabled the raster tests on Travis against nightly until we can figure out what is going wrong. I couldn't get `SilentProgress` to work - not sure it can be passed using the algorithm calling syntax in place currently.

Of course, 2.16 is due out very soon, so this is likely to become a more important issue. I'll try to do an experimental release and we'll see if others get failures.

**Comment by tomchadwin** [comment]
1.10.0  experimental released. Let's see what others find.

**Comment by tomchadwin** [comment]
No bug reports. OK for a stable release?

**Comment by tomchadwin** [comment]
Looks like we have a test failure now with 2.16:

https://travis-ci.org/tomchadwin/qgis2web/jobs/144186976

Any ideas?

**Comment by lucacasagrande** [comment]
I will take a look at this.

**Comment by tomchadwin** [comment]
See the dev list. I'm trying upgrading to GDAL2 on Travis. It's running now.

**Comment by lucacasagrande** [comment]
Yes, the parameter -te_srs srs_def was included in GDAL >= 2.0.

**Comment by tomchadwin** [comment]
I can't get GDAL2 to install under Travis. See this evening's commits. How do I do it?

**Comment by tomchadwin** [comment]
I think I got GDAL2 to install. But it seems to have uninstalled QGIS. I really wasn't expecting that. 

https://travis-ci.org/tomchadwin/qgis2web/jobs/144312199#L861
